model:
  gaussian:
    class_path: internal.models.appearance_feature_gaussian.AppearanceFeatureGaussian
    init_args:
      sh_degree: 0
      appearance_feature_dims: 64
      optimization:
        appearance_feature_lr_init: 2e-3
  renderer:
    class_path: internal.renderers.gsplat_appearance_embedding_visibility_map_renderer.GSplatAppearanceEmbeddingVisibilityMapRenderer
    init_args:
      model:
        is_view_dependent: false
  metric:
    class_path: internal.metrics.visibility_map_metrics.VisibilityMapMetrics
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser:
    class_path: PhotoTourism
    init_args:
      down_sample_factor: 2
      split_mode: "experiment"